server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cygyl?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
#    url: jdbc:mysql://192.168.200.56:3306/gyl_db?characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: gyl
#    password: gyl@123#
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapping/**/*.xml
  type-aliases-package: com/example/cygyl/model/pojo
  global-config:
    db-config:
      column-underline: true

us3:
  publicKey: TOKEN_51294e39-8b52-4efe-9a6b-fa513ec54389
  privateKey: a336594c-163f-4e00-bf2e-808dad0641b7
  region: zwkj.cn-bj
  bucket: zwkj